apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: selfsigned-cert
spec:
  commonName: dialog-flow.netservicesvm.com
  secretName: selfsigned-cert-tls
  issuerRef:
    name: self-sign-issuer
